# Numpy Basics: Arrays & Vectorized Computation

Numpy Introduction:

1. Numpy stands for Numerical Python_ It is a powerful python library used for numerical computation

2. NumPy arrays are mutable, meaning you can change their values after creation.

3. Arrays object in Numpy called "ndarray", ndarray >> N-Dimensioanl Array

4. It stores data in contegeous block of memory

In [2]:
import numpy as np

In [6]:
print(np.__version__)

1.26.4


In [8]:
array_01 = np.array([1,2,3,4,5])

print(array_01)

[1 2 3 4 5]


# Multidimensional Array_Objects

In [13]:
zero = np.zeros((4,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
one = np.ones((5,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
print(type(one))

<class 'numpy.ndarray'>


In [20]:
print(one.dtype)

float64


In [23]:
empty = np.empty((2,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

# Python List Convert Into Numpy Array

In [24]:
python_list = [1,2,3,4,5,6]

In [26]:
type(python_list)

list

In [27]:
numpy_array = np.array(python_list)

print(type(numpy_array))

<class 'numpy.ndarray'>


In [30]:
np.array(python_list)

array([1, 2, 3, 4, 5, 6])

# Arange Function Used to Create an Array just like Range function in python | It will create only 1-D Array 

In [36]:
array_02 = np.arange(1,100,10) #it creates an array from 1 to 100 with step size of 10

array_02

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

# (.shape) Function is used to check the shape of an array e.g. 1-d, 2-d, 3-d, etc

In [38]:
array_02.shape

(10,)

In [39]:
len(array_02)

10

In [40]:
array_02.size

10

# (.reshape) Function is used to reshape the array into rows and columns

In [41]:
arr = np.arange(20).reshape(4,5) 
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# How to create 2-D Array?

1. We can create 2-D array bu using arange function it will creat 1-D array then we will use reshaps function that will convert 1-D to 2-D

2. We can create 2-D array by using method that is >> np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [42]:
_2D_Array = np.array([[1,2,3,4],[5,6,7,8]])

_2D_Array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# From 1-d to 2-d array

In [43]:
_1D_Array = np.arange(10)

In [44]:
_1D_Array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# For checking the Data Types and Dimensions of Arrays 

1.   (.dtype) For checking the Data Type

2.   (.ndim) For checking the Dimensions of Array

In [45]:
_1D_Array.dtype

dtype('int32')

In [46]:
_1D_Array.ndim

1

# 0-D Array

In [48]:
np.array(45)

array(45)

# 1-D Array

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2-D Array

In [51]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# 3-D Array

In [52]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# We Have Learned 1-D array to 2-D array, Know we will learn how to convert 2-D array to 1-D array

we have 3 functions that we can used to convert the 2-D array to 1-D array 

1. ( .reshape() )

2. ( .flatten() )

3. ( .ravel() )

In [54]:
# First we create the 2-Dimensioanl Array

array2d =np.array([[1,2,3],[4,5,6]])
array2d

array([[1, 2, 3],
       [4, 5, 6]])

# By using .reshape() function

In [65]:
array2d.reshape(-1)

# The -1 argument in the reshape() function indicates that NumPy should automatically calculate the size 
# of the remaining dimension based on the total number of elements in the array, ensuring that the resulting array is 1D.

array([1, 2, 3, 4, 5, 6])

#  By using .flatten() function

In [66]:
a = np.array([[11,12,13],[14,15,16]])

In [67]:
a

array([[11, 12, 13],
       [14, 15, 16]])

In [70]:
a.flatten()  #It will return the coppy of array by converting it into 1-d array

array([11, 12, 13, 14, 15, 16])

In [71]:
a

array([[11, 12, 13],
       [14, 15, 16]])

# By Using the .ravel() function

In [72]:
b = np.array([[111,112,113],[114,115,116]])

In [73]:
b

array([[111, 112, 113],
       [114, 115, 116]])

In [75]:
b.ravel()

array([111, 112, 113, 114, 115, 116])

# Arithmatic operations with NDARRAY

1. np.random.randn(): This function is part of the NumPy library's random module, which provides various methods for generating random numbers.
2. (10): This argument specifies the shape of the output array. In this case, it's a tuple with only one element, 10, indicating that we want an array with 10 elements.

So, np.random.randn(10) generates an array with 10 random numbers sampled from a standard normal distribution. Each number in the array is drawn independently from the standard normal distribution, meaning each number has a mean of 0 and a standard deviation of 1.

In [76]:
A = np.random.randn((10))

In [77]:
B = np.random.randn((10))

In [79]:
A

array([-0.52059527, -0.47002936, -0.07752566,  2.04321212,  0.04752197,
       -1.29359976, -1.41691197,  2.36207642,  1.54955422,  1.11061749])

In [80]:
B

array([-0.2786708 , -1.88384191, -0.21697278,  0.64826278,  0.86815162,
        0.79788987,  1.23012421,  1.52848123, -0.91182764, -0.69800007])

In [81]:
A+B

array([-0.79926607, -2.35387127, -0.29449844,  2.69147491,  0.91567359,
       -0.49570989, -0.18678776,  3.89055765,  0.63772658,  0.41261742])

In [82]:
A-B

array([-0.24192447,  1.41381255,  0.13944711,  1.39494934, -0.82062965,
       -2.09148963, -2.64703618,  0.8335952 ,  2.46138186,  1.80861757])

In [83]:
C = np.array([[1,2,3],[4,5,6]])

D = np.array([[1,2,3],[4,5,6]])

In [84]:
C

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
D

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
C+D

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [87]:
C-D

array([[0, 0, 0],
       [0, 0, 0]])

In [88]:
C>D

array([[False, False, False],
       [False, False, False]])

# Indexing & Slicing

In [92]:
def inputArray(array):
    lis = list(array)
    revers = lis.strip().split(' ').reverse().float
    return revers


result = inputArray([1,2,3])
print(results)

AttributeError: 'list' object has no attribute 'strip'