# Numpy Basics: Arrays & Vectorized Computation

Numpy Introduction:

1. Numpy stands for Numerical Python_ It is a powerful python library used for numerical computation

2. NumPy arrays are mutable, meaning you can change their values after creation.

3. Arrays object in Numpy called "ndarray", ndarray >> N-Dimensioanl Array

4. It stores data in contegeous block of memory

In [2]:
import numpy as np

In [6]:
print(np.__version__)

1.26.4


In [8]:
array_01 = np.array([1,2,3,4,5])

print(array_01)

[1 2 3 4 5]


# Multidimensional Array_Objects

In [13]:
zero = np.zeros((4,4))
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
one = np.ones((5,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
print(type(one))

<class 'numpy.ndarray'>


In [20]:
print(one.dtype)

float64


In [23]:
empty = np.empty((2,3))
empty

array([[0., 0., 0.],
       [0., 0., 0.]])

# Python List Convert Into Numpy Array

In [24]:
python_list = [1,2,3,4,5,6]

In [26]:
type(python_list)

list

In [27]:
numpy_array = np.array(python_list)

print(type(numpy_array))

<class 'numpy.ndarray'>


In [30]:
np.array(python_list)

array([1, 2, 3, 4, 5, 6])

# Arange Function Used to Create an Array just like Range function in python | It will create only 1-D Array 

In [36]:
array_02 = np.arange(1,100,10) #it creates an array from 1 to 100 with step size of 10

array_02

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

# (.shape) Function is used to check the shape of an array e.g. 1-d, 2-d, 3-d, etc

In [38]:
array_02.shape

(10,)

In [39]:
len(array_02)

10

In [40]:
array_02.size

10

# (.reshape) Function is used to reshape the array into rows and columns

In [41]:
arr = np.arange(20).reshape(4,5) 
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# How to create 2-D Array?

1. We can create 2-D array bu using arange function it will creat 1-D array then we will use reshaps function that will convert 1-D to 2-D

2. We can create 2-D array by using method that is >> np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [42]:
_2D_Array = np.array([[1,2,3,4],[5,6,7,8]])

_2D_Array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# From 1-d to 2-d array

In [43]:
_1D_Array = np.arange(10)

In [44]:
_1D_Array.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# For checking the Data Types and Dimensions of Arrays 

1.   (.dtype) For checking the Data Type

2.   (.ndim) For checking the Dimensions of Array

In [45]:
_1D_Array.dtype

dtype('int32')

In [46]:
_1D_Array.ndim

1

# 0-D Array

In [48]:
np.array(45)

array(45)

# 1-D Array

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2-D Array

In [51]:
np.arange(20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# 3-D Array

In [52]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# We Have Learned 1-D array to 2-D array, Know we will learn how to convert 2-D array to 1-D array

we have 3 functions that we can used to convert the 2-D array to 1-D array 

1. ( .reshape() )

2. ( .flatten() )

3. ( .ravel() )

In [54]:
# First we create the 2-Dimensioanl Array

array2d =np.array([[1,2,3],[4,5,6]])
array2d

array([[1, 2, 3],
       [4, 5, 6]])

# By using .reshape() function

In [65]:
array2d.reshape(-1)

# The -1 argument in the reshape() function indicates that NumPy should automatically calculate the size 
# of the remaining dimension based on the total number of elements in the array, ensuring that the resulting array is 1D.

array([1, 2, 3, 4, 5, 6])

#  By using .flatten() function

In [66]:
a = np.array([[11,12,13],[14,15,16]])

In [67]:
a

array([[11, 12, 13],
       [14, 15, 16]])

In [70]:
a.flatten()  #It will return the coppy of array by converting it into 1-d array

array([11, 12, 13, 14, 15, 16])

In [71]:
a

array([[11, 12, 13],
       [14, 15, 16]])

# By Using the .ravel() function

In [72]:
b = np.array([[111,112,113],[114,115,116]])

In [73]:
b

array([[111, 112, 113],
       [114, 115, 116]])

In [75]:
b.ravel()

array([111, 112, 113, 114, 115, 116])

# Arithmatic operations with NDARRAY

1. np.random.randn(): This function is part of the NumPy library's random module, which provides various methods for generating random numbers.
2. (10): This argument specifies the shape of the output array. In this case, it's a tuple with only one element, 10, indicating that we want an array with 10 elements.

So, np.random.randn(10) generates an array with 10 random numbers sampled from a standard normal distribution. Each number in the array is drawn independently from the standard normal distribution, meaning each number has a mean of 0 and a standard deviation of 1.

In [76]:
A = np.random.randn((10))

In [77]:
B = np.random.randn((10))

In [79]:
A

array([-0.52059527, -0.47002936, -0.07752566,  2.04321212,  0.04752197,
       -1.29359976, -1.41691197,  2.36207642,  1.54955422,  1.11061749])

In [80]:
B

array([-0.2786708 , -1.88384191, -0.21697278,  0.64826278,  0.86815162,
        0.79788987,  1.23012421,  1.52848123, -0.91182764, -0.69800007])

In [81]:
A+B

array([-0.79926607, -2.35387127, -0.29449844,  2.69147491,  0.91567359,
       -0.49570989, -0.18678776,  3.89055765,  0.63772658,  0.41261742])

In [82]:
A-B

array([-0.24192447,  1.41381255,  0.13944711,  1.39494934, -0.82062965,
       -2.09148963, -2.64703618,  0.8335952 ,  2.46138186,  1.80861757])

In [83]:
C = np.array([[1,2,3],[4,5,6]])

D = np.array([[1,2,3],[4,5,6]])

In [84]:
C

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
D

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
C+D

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [87]:
C-D

array([[0, 0, 0],
       [0, 0, 0]])

In [88]:
C>D

array([[False, False, False],
       [False, False, False]])

# Indexing & Slicing

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])

In [3]:
arr1[2]

3

In [4]:
arr1[3]

4

In [18]:
arr2d = np.arange(30).reshape(6,5)

In [19]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [20]:
arr2d[0]

array([0, 1, 2, 3, 4])

In [21]:
arr2d[1]

array([5, 6, 7, 8, 9])

In [22]:
arr2d[1][3]

8

In [23]:
arr2d[arr2d>5] ##Boolean indexing

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29])

In [24]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

# Fancy Indexing


if we want to specific rows more then 1 from 2d array, then we will use fancy indexing like below

In [26]:
arr2d[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

# Element-Wise Function

In [14]:
import numpy as np

In [20]:
x = np.array([101,911,8,6,11])

In [21]:
print(np.sqrt(x)) #Each element in the array result is the square root of the corresponding element in the array x.

[10.04987562 30.18277655  2.82842712  2.44948974  3.31662479]


In [22]:
print(np.power(x,2))

[ 10201 829921     64     36    121]


In [23]:
y = np.array([110,91,81,61,11])

In [24]:
np.maximum(x,y) #Each element in the resulting array is the maximum of the corresponding elements in x and y.

array([110, 911,  81,  61,  11])

# NP-Where function 


The first argument (arr > 2) is the condition. It checks each element of the array arr to see if it's greater than 2.

The second argument (10) is the value that will replace the elements where the condition is True. So, if an element is greater than 2, it will be replaced by 10.

The third argument (arr) is the value that will replace the elements where the condition is False. So, if an element is not greater than 2, it remains unchanged.

In [32]:
salary = np.array([10000, 20000, 30000,40000])


results = np.where(salary>20000, 35000,salary)

print(results)

[10000 20000 35000 35000]


# Mathematical & Statistical Method

Mean Function 

In [33]:
a = np.array([1,2,3,4,5,6])

print(a.mean())

3.5


cumsum() function >> cumulative sum of array elements

The first element in the cumulative sum array is the same as the first element in the original array (1).

The second element in the cumulative sum array is the sum of the first two elements in the original array (1 + 2 = 3).

The third element in the cumulative sum array is the sum of the first three elements in the original array (1 + 2 + 3 = 6).

In [34]:
print(a.cumsum())

[ 1  3  6 10 15 21]


cumprod() >> cumulative product of array element

In [35]:
print(a.cumprod())

[  1   2   6  24 120 720]


In [38]:
b = np.array([1,1,2,3,4,45,5])  #if the array has some same values multiple time like this [1,1,2,3,3], it will only once

print(np.unique(b))

[ 1  2  3  4  5 45]


# File Input/Output

In [39]:
X = [1,4,5,7]
Y = [8,9,10]

np.save('textx',X)  #It will save the text file in the same directory

# Numpy Linear Algebra Functions

In [1]:
import numpy as np

In [10]:
x = np.random.randn(3,2)

y = np.random.randn(2,3)
x.dot(y)

array([[ 0.43005601,  0.15783621,  0.43261693],
       [-1.49221304,  0.47150238, -1.22919505],
       [-0.55016876,  0.31494861, -0.41554923]])

In [11]:
x

array([[ 0.34885394,  0.25173951],
       [-1.23310142,  1.00608889],
       [-0.45777129,  0.63117596]])

In [12]:
x.transpose()

array([[ 0.34885394, -1.23310142, -0.45777129],
       [ 0.25173951,  1.00608889,  0.63117596]])

In [13]:
x.trace() # 
The x.trace() #method in NumPy computes the sum along the diagonal of the array x.

1.3549428357941

# Pseudo Random Number Generator (PRNG):

A pseudo-random number generator is a computer program or algorithm that produces numbers that appear random, but are actually generated by a deterministic process. In simpler terms, it's a tool used by computers to create sequences of numbers that seem random, but are actually generated using a specific formula. These numbers are not truly random because they are generated by an algorithm, but they're unpredictable enough for most practical purposes.

# np.random.normal()

This function generates random numbers from a normal distribution (Gaussian distribution). It takes parameters for mean, standard deviation, and the size of the output array. Here's an example:

In [15]:
import numpy as np

# Generate 10 random numbers from a normal distribution with mean 0 and standard deviation 1
random_numbers = np.random.normal(1, 2, 10)

print(random_numbers)

[-1.43049641  0.49057668  1.60545916  3.27691065  1.25977911  1.70909789
  0.54274473  1.79948813  2.36820573  0.27155687]


# np.random.seed()

This function sets the seed for the random number generator. This is useful for reproducibility; setting the seed to a specific value ensures that the same sequence of random numbers is generated each time the code is run. Here's an example:

In [28]:
import numpy as np

# Set the seed to 42
np.random.seed(2)

# Generate 5 random numbers
random_numbers = np.random.random(5)

print(random_numbers)

#This will output an array of 5 random numbers, but because we set the seed to 42, running this code multiple times will always produce the same sequence of random numbers.

[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678 ]


# np.random.gamma()

This function generates random numbers from a gamma distribution. It takes parameters for shape and scale, as well as the size of the output array. Here's an example:

In [23]:
random_numbers = np.random.gamma(2, 2, 10)

print(random_numbers)

[4.10697087 6.68243999 2.04721274 2.15290884 0.11489537 6.43856384
 2.34577209 1.76041404 1.95788388 5.12707361]


# Concatenate

V-Stack: Row-Wise

H-Stack: Col-Wise

In [29]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])

arr2 = np.array([[9,10,11,12],[13,14,15,16]])



# V-Stack: Row-Wise

In [30]:
np.concatenate((arr1,arr2), axis=0) #axis 0 mean it will concatenate and increse the number of rows 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

# H-Stack: Col-Wise

In [31]:
np.concatenate((arr1,arr2), axis=1) #axis 1 mean it will concatenate and increse the number of Col 

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

# We can also use np.vstack and np.hstack

In [32]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

# Spliting of arays

Split the into multiple arrays along x-axis

In [39]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

np.split(arr1,[2,4])  # in this [2,4] means that we have to split the array 1st from index 2 and then again aplit from index 4

[array([1, 2]), array([3, 4]), array([ 5,  6,  7,  8,  9, 10])]

# If we have to split 2-D Array? then we will use its axis o or 1 for col or rows

In [41]:
arr2d = np.arange(10).reshape(5,2)

In [42]:
arr2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
np.split(arr2d,[2],axis=0)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7],
        [8, 9]])]

# Tile & Repeat

np.tile(array, reps): Repeats the elements of an array along specified axes.
    
np.repeat(array, repeats): Repeats each element of an array a specified number of times.

In [44]:
arr1d = np.array([1,2,3,4,5,6,7,8,9])

In [45]:
arr1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.repeat(arr1,2) # we have to repeat arr1 and 2 parameter mean that we want every elennt in two times repeatations

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,
        9, 10, 10])

In [51]:
np.tile(arr1d,2)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Problem solving _ Assignment 2 

# Question 1

Convert a 1D array to a 2D array with 2 rows?

Desired output::¶
        
array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

In [60]:
array1d = np.arange(10)
array2d = array1d.reshape(2,5)
print(array2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# Question 2

How to stack two arrays vertically?

Desired Output::
        
array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])


In [93]:
arry1 = np.arange(10)
arry2 = np.full(10, 1)

In [94]:
arry1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
arry2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [96]:
a = np.split(arry1,[5])

In [97]:
print(a)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [98]:
b = np.split(arry2,[5])

In [99]:
b

[array([1, 1, 1, 1, 1]), array([1, 1, 1, 1, 1])]

In [100]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Question:3 How to stack two arrays horizontally?


Desired Output::
        
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [102]:
arr1 = np.arange(10)
arr2 = np.full(10, 1)

In [103]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [105]:
split_arr1 = np.split(arr1,[5])

In [106]:
split_arr1

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [107]:
split_arr2 = np.split(arr2,[5])

In [108]:
split_arr2

[array([1, 1, 1, 1, 1]), array([1, 1, 1, 1, 1])]

In [112]:
Horizontal_Array = np.hstack((split_arr1,split_arr2))

In [113]:
Horizontal_Array

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

# Question:4 How to convert an array of arrays into a flat 1d array?


Desired Output::
        
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
array_of_arrays = np.arange(10).reshape(5,2)

In [119]:
print(array_of_arrays)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [120]:
flat_1d_array = array_of_arrays.flatten()

In [121]:
flat_1d_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Question:5 How to Convert higher dimension into one dimension?


Desired Output::
array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [122]:
arr3d = np.array([[[0,1,2,3,4],[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]])

In [123]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [124]:
arr3d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Question:6 Convert one dimension to higher dimension?


Desired Output::
array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [125]:
arr1d = np.arange(15)

In [126]:
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [128]:
arr1d.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

# Question:7 Create 5x5 an array and find the square of an array?

In [129]:
arr5by5 = np.arange(25).reshape(5,5) 

In [130]:
arr5by5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [133]:
squared_arr = arr5by5 ** 2

In [134]:
squared_arr

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

# Question:8 Create 5x6 an array and find the mean?¶

In [135]:
arr5by6 = np.arange(30).reshape(5,6) 

In [136]:
arr5by6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [137]:
np.mean(arr5by6)

14.5

# Question:9 Find the standard deviation of the previous array in Q8?

In [138]:
np.std(arr5by6)

8.65544144839919

# Question:10 Find the median of the previous array in Q8?

In [139]:
np.median(arr5by6)

14.5

# Question:11 Find the transpose of the previous array in Q8?

In [140]:
arr5by6

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [141]:
arr5by6.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

# Question:12 Create a 4x4 an array and find the sum of diagonal elements?

In [142]:
arr4by4 = np.arange(16).reshape(4,4)

In [143]:
arr4by4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [144]:
np.trace(arr4by4)

30

# Question:13 Find the determinant of the previous array in Q12?

In [145]:
np.linalg.det(arr4by4)

0.0

# Question:14 Find the 5th and 95th percentile of an array?¶

In [146]:
arr4by4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [147]:
np.percentile(arr4by4,[50,95])

array([ 7.5 , 14.25])

# Question:15 How to find if a given array has any null values?

In [149]:
array = np.array([1,2,3,4,np.nan,5,np.nan])

In [150]:
array

array([ 1.,  2.,  3.,  4., nan,  5., nan])

In [155]:
np.isnan(array)

array([False, False, False, False,  True, False,  True])

In [161]:
nan_indices = np.where(np.isnan(array))


for index in nan_indices[0]:
    print("Index:", index, ", Value:", array[index])


Index: 4 , Value: nan
Index: 6 , Value: nan


# Assignment 1 Questions 

# Question 1 

Import the numpy package under the name np

In [1]:
import numpy as np

# Question 2

Create a null vector of size 10

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Question 3

Create a vector with values ranging from 10 to 49

In [4]:
vec = np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Question 4

Find the shape of previous array in question 3

In [5]:
np.shape(vec)

(40,)

# Question 5 

Print the type of the previous array in question 3

In [7]:
vec.dtype

dtype('int32')

# Question 6 

Print the numpy version and the configuration

In [8]:
print(np.__version__)

1.26.4


# Question 7

Print the dimension of the array in question 3

In [9]:
vec.ndim

1

# Question 8

Create a boolean array with all the True values

In [10]:
boolean_array = np.array([True, True,True,True])
boolean_array

array([ True,  True,  True,  True])

# Question 9

Create a two dimensional array

In [11]:
arr2d = np.arange(10).reshape(5,2)
arr2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Question 10

Create a three dimensional array

In [12]:
arr2d = np.array([[[1,2,3,4],[5,6,7,8]]])

In [13]:
arr2d

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

# Question 11

Reverse a vector (first element becomes last)

In [14]:
arr1 = np.arange(10)

In [15]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.flip(arr1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Question 12

Create a null vector of size 10 but the fifth value which is 1

In [25]:
null_vec = np.zeros(10, dtype=int)

In [27]:
null_vec[4]=1

In [28]:
null_vec

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

# Question 13

Create a 3x3 identity matrix

In [33]:
identity_Matrics = np.eye(3, dtype=int)

In [34]:
identity_Matrics

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Question 14

Convert the data type of the given array from int to float

arr = np.array([1, 2, 3, 4, 5])


In [39]:
arr = np.array([1, 2, 3, 4, 5], dtype=float)

In [40]:
arr.dtype

dtype('float64')

In [42]:
arr

array([1., 2., 3., 4., 5.])

# Question 15

Multiply arr1 with arr2

arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [44]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])

arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [47]:
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

# Question 16

Make an array by comparing both the arrays provided below

arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

In [9]:
import numpy as np

arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])

arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

new_array = np.vstack((arr1,arr2))
print(new_array)

np.sort(new_array)
np.unique(new_array)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 0.  4.  1.]
 [ 7.  2. 12.]]


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7., 12.])

# Question 17 

Extract all odd numbers from arr with values(0-9)

In [19]:
arr = np.arange(10)

arr
extract_odd = []
for i in arr:
    if i%2 != 0:
        extract_odd.append(i)
extracted_array = np.array(extract_odd)    
print(extracted_array)

[1 3 5 7 9]


# Question 18

Replace all odd numbers to -1 from previous array

In [28]:
extracted_array[:]=-1
print(extracted_array)

[-1 -1 -1 -1 -1]


# Question 19

arr = np.arange(10)

Replace the values of indexes 5,6,7 and 8 to 12

In [29]:
arr = np.arange(10)

arr[5:9]=12
arr

# Question 20 

Create a 2d array with 1 on the border and 0 inside

In [66]:
arr2d = np.zeros((6, 5))

# Set the first and last rows to 1
arr2d[[0, -1], :] = 1

# Set the first and last columns to 1
arr2d[:, [0, -1]] = 1

print(arr2d)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [67]:

arr2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [68]:
arr2d[[0,-1],:]=2
arr2d[:,[0,-1]]=2
arr2d

array([[2., 2., 2., 2., 2.],
       [2., 0., 0., 0., 2.],
       [2., 0., 0., 0., 2.],
       [2., 0., 0., 0., 2.],
       [2., 0., 0., 0., 2.],
       [2., 2., 2., 2., 2.]])

# Question 21

Replace the value 5 to 12

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])    

In [70]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [76]:
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

# Question 22

Convert all the values of 1st array to 64

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [78]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [81]:
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Question 23

Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [82]:
arr2d = np.arange(10).reshape(5,2)
arr2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [83]:
arr2d[0]

array([0, 1])

# Question 24 

Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [84]:
arr2d = np.arange(10).reshape(5,2)
arr2d

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [85]:
arr2d[1][1]

3

# Question 25 

Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [92]:
arr2d = np.arange(10).reshape(5,2)
arr2d


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [93]:
arr2d[:2, 1]

array([1, 3])

# Question 26

Create a 10x10 array with random values and find the minimum and maximum values

In [100]:
array = np.random.randn(10,10)

print(array.max())
print(array.min())

2.316535071133585
-2.3311682673007526


In [101]:
array

array([[-0.09937705, -0.7483078 , -0.02150046,  0.34709339,  0.64892844,
         1.55147846,  0.57115162, -0.77138433,  0.79670346, -0.39809998],
       [ 0.90750095, -0.08419533,  1.34854783,  0.04644858, -1.04068149,
         1.17343123, -1.12727801, -0.12200813, -0.00449804,  1.78189733],
       [-1.62423855,  1.37170854, -1.63107292,  0.22003482, -0.63649764,
         0.02384493, -0.9876899 , -0.93728239,  1.3962754 ,  0.0675545 ],
       [ 0.32214623,  0.1166152 ,  0.43353942, -1.74383754,  1.14904652,
        -0.58154379,  0.67212613,  0.9640916 ,  2.31091856, -0.19476838],
       [-0.58773077, -1.18199648,  0.32248084,  0.67945277,  0.14006496,
        -0.24061769,  0.60250676,  0.53984736,  1.05084847,  0.76174896],
       [ 0.99505264,  2.31653507, -0.26772032, -0.34173681, -1.16732744,
         0.45659723,  1.17393542,  0.33942018, -2.33116827,  1.11149681],
       [ 1.88732828,  1.36661895,  1.21780071, -1.4919174 , -0.40321208,
         0.15647248, -0.91208895,  0.63410805

# Question 27

Find the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])


In [102]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 

In [103]:
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [105]:
np.intersect1d(a,b)

array([2, 4])

# Question 28

Find the positions where elements of a and b match

a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])


In [106]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 

In [107]:
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [122]:
np.where(a == b)[0]

array([1, 3, 5, 7], dtype=int64)

# Question 29

Find all the values from array data where the values from array names are not equal to Will

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)


In [125]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 

In [126]:
data = np.random.randn(7, 4)

In [127]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [128]:
data

array([[ 1.30195854, -1.90033474, -0.96348115, -1.596379  ],
       [ 0.78838459,  1.83475096,  1.4111387 ,  1.11857521],
       [-0.42029807, -1.76072062,  0.6218547 , -0.84329974],
       [-0.96181985,  0.7422104 ,  1.00825985, -2.81141844],
       [ 0.78106292,  0.1209458 ,  1.63836022, -0.67839049],
       [ 0.6634984 ,  0.342187  ,  0.48686526, -1.06893887],
       [ 0.09757254,  0.40105865, -1.57844996,  0.65637627]])

In [130]:
not_will_indices = np.where(names != 'Will')[0]


filtered_data = data[not_will_indices]
filtered_data

array([[ 1.30195854, -1.90033474, -0.96348115, -1.596379  ],
       [ 0.78838459,  1.83475096,  1.4111387 ,  1.11857521],
       [-0.96181985,  0.7422104 ,  1.00825985, -2.81141844],
       [ 0.6634984 ,  0.342187  ,  0.48686526, -1.06893887],
       [ 0.09757254,  0.40105865, -1.57844996,  0.65637627]])

In [131]:
not_will_indices

array([0, 1, 3, 5, 6], dtype=int64)

Explation of the above code 

np.where(names != 'Will')[0] finds the positions where the elements in the names array are not equal to 'Will'.

data[not_will_indices] selects the rows from the data array corresponding to the positions where names are not equal to 'Will'.


The selected rows are stored in the variable filtered_data.

# Question 30

Find all the values from array data where the values from array names are not equal to Will and Joe

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

In [132]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 


In [133]:
data = np.random.randn(7, 4)

In [134]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [135]:
data

array([[-0.74693457, -1.50167929, -0.62826119,  1.55365231],
       [-0.30338287,  0.01429118,  0.66910735,  0.1380903 ],
       [-0.05366858,  1.05774163,  1.52864395, -0.30455661],
       [-2.20538501,  0.46407925, -0.24189827,  2.26222693],
       [-0.88245729,  1.06255388, -0.54994977, -0.00723319],
       [-0.38725929, -1.1009188 ,  0.92298005, -0.27663196],
       [ 0.0340775 , -1.00066611, -0.48845311, -0.44777309]])

In [140]:
not_matched_mask = ~np.isin(names, ["Will", "Joe"])


filtered_data = data[not_matched_mask]

print(filtered_data)

[[-0.74693457 -1.50167929 -0.62826119  1.55365231]
 [-2.20538501  0.46407925 -0.24189827  2.26222693]]


# Question 31

Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [5]:
import numpy as np

arr2d = np.arange(1,16, dtype=float).reshape(5,3)

arr2d

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

# Question 32

Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [7]:
arr = np.arange(1, 17, dtype=float)


arr_3d = arr.reshape(2, 2, 4)

print(arr_3d)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


# Question 33

Swap axes of the array you created in Question 32

In [8]:
arr_3d

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]],

       [[ 9., 10., 11., 12.],
        [13., 14., 15., 16.]]])

In [9]:
arr_swapped = arr_3d.transpose(1, 0, 2)
print(arr_swapped)

[[[ 1.  2.  3.  4.]
  [ 9. 10. 11. 12.]]

 [[ 5.  6.  7.  8.]
  [13. 14. 15. 16.]]]


# Question 34

Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [10]:
arr = np.arange(11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

# Question 35

Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [23]:
array1 = np.random.rand(12)
array2 = np.random.rand(12)


max_array = np.maximum(array1, array2)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nMaximum values between corresponding elements:")
print(max_array)

Array 1:
[0.07630829 0.77991879 0.43840923 0.72346518 0.97798951 0.53849587
 0.50112046 0.07205113 0.26843898 0.4998825  0.67923    0.80373904]

Array 2:
[0.38094113 0.06593635 0.2881456  0.90959353 0.21338535 0.45212396
 0.93120602 0.02489923 0.60054892 0.9501295  0.23030288 0.54848992]

Maximum values between corresponding elements:
[0.38094113 0.77991879 0.43840923 0.90959353 0.97798951 0.53849587
 0.93120602 0.07205113 0.60054892 0.9501295  0.67923    0.80373904]


# Question 36

Find the unique names and sort them out!

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


In [24]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [27]:
uniq = np.unique(names)

In [28]:
uniq.sort()

In [29]:
uniq

array(['Bob', 'Joe', 'Will'], dtype='<U4')

# Question 37

From array a remove all items present in array b

a = np.array([1,2,3,4,5]) b = np.array([5,6,7,8,9])


In [30]:
a = np.array([1,2,3,4,5])

In [34]:
b = np.array([5,6,7,8,9])

In [38]:
mask = np.isin(a,b, invert=True)

In [39]:
result = a[mask]

print(result)

[1 2 3 4]


# Question 38

Following is the input NumPy array delete column two and insert following new column in its place.

sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = numpy.array([[10,10,10]])

In [41]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

newColumn = np.array([[10,10,10]])

In [42]:
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [43]:
newColumn

array([[10, 10, 10]])

In [45]:
sampleArray[:,1] = newColumn

In [46]:
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

# Question 39

x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


Find the dot product of the above two matrix

In [47]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])

In [48]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [49]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [50]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [51]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

# Question 40

Generate a matrix of 20 random values and find its cumulative sum

In [52]:
matrix = np.random.randn(20)

In [53]:
matrix

array([ 1.65069969,  0.15433554, -0.38713994,  2.02907222, -0.04538603,
       -1.4506787 , -0.40522786, -2.2883151 ,  1.04939655, -0.41647432,
       -0.74255353,  1.07247013, -1.65107559,  0.53542936, -2.0644148 ,
       -0.66215934, -1.20421985,  1.46197563,  1.76616088, -0.32941375])

In [54]:
np.cumsum(matrix)

array([ 1.65069969,  1.80503523,  1.41789528,  3.4469675 ,  3.40158147,
        1.95090278,  1.54567492, -0.74264018,  0.30675637, -0.10971795,
       -0.85227148,  0.22019865, -1.43087693, -0.89544758, -2.95986238,
       -3.62202172, -4.82624157, -3.36426594, -1.59810506, -1.92751881])

# Question 41

create a 2d Array with a 60 elements

In [1]:
import numpy as np
arra2d =np.arange(60).reshape(4,15)
arra2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])